version: "3.9"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helpdesk-backend
    # ให้รับ request แค่จากเครื่อง host (Nginx จะมาเรียก)
    #ports:
    #  - "127.0.0.1:3000:3000"
    network_mode: host
    environment:
      - TZ=Asia/Bangkok
      # ฝั่ง backend ใช้ URL นี้ตอน redirect / CORS
      - FRONTEND_URL=https://itsupport.sru.ac.th

      # === Google OAuth ===
      - GOOGLE_CLIENT_ID=587858471059-3higpfbv1pnrdiok0ds0v0459n30btei.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=https://itsupport.sru.ac.th/auth/google/redirect
      # GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/redirect

      - NODE_ENV=production
      - COOKIE_SECURE=false
      - JWT_SECRET=CCISRUCOM
      - JWT_EXPIRES_IN=7d

      # DB connection (ใช้ service name db)
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=3306
      - DATABASE_USER=itsupport_user
      - DATABASE_PASSWORD=OLSsQ_D}u6w=?u}#
      - DATABASE_NAME=itsupport_db

      # === SMTP Email ===
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=software.dev@sru.ac.th
      - SMTP_PASS=clhvrageredavkpr
      - SMTP_FROM=software.dev@sru.ac.th

      # === Telegram ===
      - TELEGRAM_BOT_TOKEN=8350312225:AAEaJ0eZeJ1Oxy7EubTON27ZIPodRxTzCnA
      - TELEGRAM_CHAT_ID=-4828646624

    restart: unless-stopped
    command: >
      sh -c "
        node dist/seeds/seed-roles.js &&
        node dist/main.js
      "
    networks:                # 👈 เพิ่มตรงนี้
      - helpdesk-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helpdesk-frontend
    # เปิดให้ Nginx บน host ยิงเข้าเท่านั้น
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

